language: ruby
bundler_args: --retry=3 --jobs=8 --no-deployment
cache: bundler
sudo: false
rvm:
  - 2.2.5
  - 2.2.6
  - 2.3.0
  - 2.3.1
  - 2.3.2
  - 2.3.3
  - 2.4.1
  - ruby-head
gemfile:
  - gemfiles/rails_5.1.gemfile
  - gemfiles/rails_5.0.gemfile
  - gemfiles/rails_4.2.gemfile
matrix:
  allow_failures:
    - rvm: ruby-head
  fast_finish: true
