language: ruby
bundler_args: --retry=3 --jobs=8 --no-deployment
cache: bundler
sudo: false
rvm:
  - 2.0.0
  - 2.1
  - 2.2.2
  - 2.2.1
  - 2.2.0
  - ruby-head
matrix:
  allow_failures:
    - rvm: 2.2.1
    - rvm: 2.2.0
    - rvm: ruby-head
  fast_finish: true
